---
title: "DSlecture12"
output: html_document
---

```{r set, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(rvest)
library(httr)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## scrape a table

I want the first table from [this page](http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)


read in html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

```

extract table, focus on first 1
```{r}
tble_marj =
  drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```


## Star wars movie infor

i want the data from [here](https://www.imdb.com/list/ls070150896/)

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)


```


grab elements that i want

```{r}
title_vec=
  swm_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  html_text()

gross_rev_vec =
  swm_html %>% 
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

runtime_vec =
  swm_html %>% 
  html_nodes(css = ".runtime") %>% 
  html_text()

swm_df =
  tibble(
    title = title_vec,
    gross_rev = gross_rev_vec,
    runtime = runtime_vec
  )
```

## get some water

coming from API

```{r}
nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")


nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()

```


##BRFSS

```{r}
brfss_2010 =
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

## some data are not so nice
 pokeman
 
```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>% 
  content

poke$name
```
 




























